import Head from 'next/head'
import Image from 'next/image'
import { Fragment } from 'react'
import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faRightToBracket } from '@fortawesome/free-solid-svg-icons'
import Logo from '../assets/logo-bg.png'
import Link from 'next/link'

// import Card from './components/card'

export default function Home({ data }: any) {

  return (
    <Fragment>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* NavBar */}
      <nav className="w-screen h-[50px] fixed flex justify-around items-center bg-opacity-50 z-50 px-6 backdrop-filter backdrop-blur-xl">
        <div className='flex items-center -ml-[210px] cursor-pointer'>
          <Image className='w-[40px]' src={ Logo } alt='' />
          {/* <div className="text-2xl font-bold ml-2">{ data.name }</div> */}
        </div>
        <Link href="/signin">
          <FontAwesomeIcon className="w-[50px] h-[50px] p-[10px] text-white transition duration-300 hover:text-zinc-500 rounded-2xl -mr-[200px] cursor-pointer" icon={ faRightToBracket } />
        </Link>
      </nav>

      <main className="w-[45%] h-[1500px] flex justify-center">

        <div className="profile pt-[12rem]">
          <div className="text-[50px] font-bold">{ data.name }</div>
        </div>

        {/* <Card /> */}

      </main>
    </Fragment>
  )
}

export async function getServerSideProps() {

  const res = await fetch('http://localhost:3000/api/hello', {
    method: 'POST',
    headers: {
        "Content-Type": "application/json",
    },
    body: JSON.stringify({ name: "Blog" })
  })
  const data = await res.json()

  return { props: { data } }
}