import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { Fragment, useEffect } from 'react'
import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
import Cookies from 'js-cookie'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faRightToBracket } from '@fortawesome/free-solid-svg-icons'

import Logo from '../assets/logo-bg.png'

import Card from './components/card'

export default function Home({ data }: any) {
  const router = useRouter()

  const Contents = [
    {
      title: 'Hello, World!',
      sub: '안녕하세요'
    },
    {
      title: 'Hello, World!',
      sub: '안녕하세요'
    },
    {
      title: 'Hello, World!',
      sub: '안녕하세요'
    },
    {
      title: 'Hello, World!',
      sub: '안녕하세요'
    },
    {
      title: 'Hello, World!',
      sub: '안녕하세요'
    },
    {
      title: 'Hello, World!',
      sub: '안녕하세요'
    },
    {
      title: 'Hello, World!',
      sub: '안녕하세요'
    },
    {
      title: 'Hello, World!',
      sub: '안녕하세요'
    }
  ]
  const List = Contents.map((data) => (<Card title={data.title} sub={data.sub} />))

  useEffect(() => {
    if (Cookies.get("isAcced") !== null || Cookies.get("isAcced") !== '') {
      console.log(`login successful: ${Cookies.get("isAcced")}`)
    }
  }, [])
  
  return (
    <Fragment>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* NavBar */}
      <nav className="w-screen h-[50px] fixed flex justify-around items-center bg-opacity-50 z-50 backdrop-filter backdrop-blur-xl">
        <div className='flex items-center pr-[350px] cursor-pointer'>
          <Image className='w-[40px]' src={ Logo } alt='' />
          {/* <div className="text-2xl font-bold ml-2">{ data.name }</div> */}
        </div>
        <Link href="/signin">
          { Cookies.get("isAcced") == null || Cookies.get("isAcced") == '' ?
            // <FontAwesomeIcon className="w-[50px] h-[50px] p-[10px] text-white transition duration-300 hover:text-zinc-500 rounded-2xl pl-[0px] cursor-pointer" icon={ faRightToBracket } />
            <button className='font-bold text-zinc-800 text-ld rounded-[12px] bg-white w-24 h-8 transition duration-300 hover:scale-105 hover:brightness-75'>Login</button>
          : <button className='font-bold text-xl' onClick={ () => { Cookies.set("isAcced", ''); router.push('/') } }>Logout</button> }
        </Link>
      </nav>

      <main className="w-screen flex flex-col items-center">

        {/* <div className="profile -mt-[600px]">
          <div className="text-[50px] font-bold ">{ data.name }{', ' + Cookies.get("isAcced") || ''}!</div>
        </div> */}

        <div className="pt-[200px] font-bold text-2xl flex flex-wrap">
          {List}
        </div>

      </main>
    </Fragment>
  )
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/hello', {
    method: 'POST',
    headers: {
        "Content-Type": "application/json",
    },
    body: JSON.stringify({ name: `Hello, World` })
  })
  const data = await res.json()

  return { props: { data } }
}